"""Independent version constants for KFlow's public protocols."""

METADATA_SCHEMA_VERSION = 3
PROJECT_GRAPH_SCHEMA_VERSION = 3
CONTEXT_SCHEMA_VERSION = 4
IMPACT_SCHEMA_VERSION = 4
REVIEW_ORDER_SCHEMA_VERSION = 3
MUTATION_SCHEMA_VERSION = 4
TASK_QUERY_SCHEMA_VERSION = 3
DOWNSTREAM_CONFIRM_SCHEMA_VERSION = 1


__all__ = [
    "CONTEXT_SCHEMA_VERSION",
    "DOWNSTREAM_CONFIRM_SCHEMA_VERSION",
    "IMPACT_SCHEMA_VERSION",
    "METADATA_SCHEMA_VERSION",
    "MUTATION_SCHEMA_VERSION",
    "PROJECT_GRAPH_SCHEMA_VERSION",
    "REVIEW_ORDER_SCHEMA_VERSION",
    "TASK_QUERY_SCHEMA_VERSION",
]
